app:
  secrets: /etc/experiment
  image_name: container_experiment
  workdir: /home/epsilond1/experiment
  repo: https://github.com/Epsilond1/experiment.git
prompter:
  secrets: /etc/prompter/
  image_name: prompter
  workdir: ~/prompter
  repo: https://github.com/Epsilond1/prompter.git
