app:
  secrets: /etc/experiment
  image_name: container_experiment
  workdir: /home/epsilond1/experiment
  repo: https://github.com/Epsilond1/experiment.git
  branch: master
  port_external: 80
  port_internal: 4000
  protocol: tcp
